---
- name: Get Username and Password.
  hosts: all
  connection: local
  tags:
    - always
  gather_facts: no

  tasks:
    - name: remove host build temp directory
      file: path={{ build_dir }} state=absent
    - name: create host build temp directory
      file: path={{ build_dir }} state=directory